server:
  port: 8080
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: sa
      driverClassName: org.h2.Driver
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        show_sql: false
        format_sql: false
logging:
  level:
    org:
      hibernate:
        type: error